import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import ServiceSection from "@/components/ServiceSection";
import Footer from "@/components/Footer";
import ContactSection from "@/components/ContactSection";
import Category from "@/sections/Category";
import CounterSection from "@/components/CounterSection";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "codevalley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
      <Header />  
    <HeroSection/>     
       <Category />
       <ServiceSection />
        <CounterSection /> 
        <ContactSection />
      < Footer />    
        {children}
      </body>
    </html>
  );
}
